/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesDriftwoodDunesGuideRouteImport } from './routes/guides.driftwood-dunes-guide'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as Properties18OceanBlvdRouteImport } from './routes/properties.18-ocean-blvd'
import { Route as PropertiesCedarHollowCabinRouteImport } from './routes/properties.cedar-hollow-cabin'
import { Route as PropertiesFirelightCottageRouteImport } from './routes/properties.firelight-cottage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDriftwoodDunesGuideRoute =
  GuidesDriftwoodDunesGuideRouteImport.update({
    id: '/guides/driftwood-dunes-guide',
    path: '/guides/driftwood-dunes-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const Properties18OceanBlvdRoute = Properties18OceanBlvdRouteImport.update({
  id: '/properties/18-ocean-blvd',
  path: '/properties/18-ocean-blvd',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesCedarHollowCabinRoute =
  PropertiesCedarHollowCabinRouteImport.update({
    id: '/properties/cedar-hollow-cabin',
    path: '/properties/cedar-hollow-cabin',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertiesFirelightCottageRoute =
  PropertiesFirelightCottageRouteImport.update({
    id: '/properties/firelight-cottage',
    path: '/properties/firelight-cottage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/guides/driftwood-dunes-guide': typeof GuidesDriftwoodDunesGuideRoute
  '/properties/18-ocean-blvd': typeof Properties18OceanBlvdRoute
  '/properties/cedar-hollow-cabin': typeof PropertiesCedarHollowCabinRoute
  '/properties/firelight-cottage': typeof PropertiesFirelightCottageRoute
  '/guides/': typeof GuidesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/guides/driftwood-dunes-guide': typeof GuidesDriftwoodDunesGuideRoute
  '/properties/18-ocean-blvd': typeof Properties18OceanBlvdRoute
  '/properties/cedar-hollow-cabin': typeof PropertiesCedarHollowCabinRoute
  '/properties/firelight-cottage': typeof PropertiesFirelightCottageRoute
  '/guides': typeof GuidesIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/guides/driftwood-dunes-guide': typeof GuidesDriftwoodDunesGuideRoute
  '/properties/18-ocean-blvd': typeof Properties18OceanBlvdRoute
  '/properties/cedar-hollow-cabin': typeof PropertiesCedarHollowCabinRoute
  '/properties/firelight-cottage': typeof PropertiesFirelightCottageRoute
  '/guides/': typeof GuidesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/guides/driftwood-dunes-guide'
    | '/properties/18-ocean-blvd'
    | '/properties/cedar-hollow-cabin'
    | '/properties/firelight-cottage'
    | '/guides/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/guides/driftwood-dunes-guide'
    | '/properties/18-ocean-blvd'
    | '/properties/cedar-hollow-cabin'
    | '/properties/firelight-cottage'
    | '/guides'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/guides/driftwood-dunes-guide'
    | '/properties/18-ocean-blvd'
    | '/properties/cedar-hollow-cabin'
    | '/properties/firelight-cottage'
    | '/guides/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ReviewsRoute: typeof ReviewsRoute
  GuidesDriftwoodDunesGuideRoute: typeof GuidesDriftwoodDunesGuideRoute
  Properties18OceanBlvdRoute: typeof Properties18OceanBlvdRoute
  PropertiesCedarHollowCabinRoute: typeof PropertiesCedarHollowCabinRoute
  PropertiesFirelightCottageRoute: typeof PropertiesFirelightCottageRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/driftwood-dunes-guide': {
      id: '/guides/driftwood-dunes-guide'
      path: '/guides/driftwood-dunes-guide'
      fullPath: '/guides/driftwood-dunes-guide'
      preLoaderRoute: typeof GuidesDriftwoodDunesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/18-ocean-blvd': {
      id: '/properties/18-ocean-blvd'
      path: '/properties/18-ocean-blvd'
      fullPath: '/properties/18-ocean-blvd'
      preLoaderRoute: typeof Properties18OceanBlvdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/cedar-hollow-cabin': {
      id: '/properties/cedar-hollow-cabin'
      path: '/properties/cedar-hollow-cabin'
      fullPath: '/properties/cedar-hollow-cabin'
      preLoaderRoute: typeof PropertiesCedarHollowCabinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/firelight-cottage': {
      id: '/properties/firelight-cottage'
      path: '/properties/firelight-cottage'
      fullPath: '/properties/firelight-cottage'
      preLoaderRoute: typeof PropertiesFirelightCottageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ReviewsRoute: ReviewsRoute,
  GuidesDriftwoodDunesGuideRoute: GuidesDriftwoodDunesGuideRoute,
  Properties18OceanBlvdRoute: Properties18OceanBlvdRoute,
  PropertiesCedarHollowCabinRoute: PropertiesCedarHollowCabinRoute,
  PropertiesFirelightCottageRoute: PropertiesFirelightCottageRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
